# Generated by Django 5.2.6 on 2025-09-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('playbooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbook',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='playbook_tags', to='core.tag'),
        ),
    ]
